source 'https://api.berkshelf.com'

cookbook 'sudo'
cookbook 'ruby_build'
cookbook 'chef-solo-search'
cookbook 'selinux'
cookbook 'mariadb'
cookbook 'redis', git: 'https://github.com/miah/chef-redis.git'
cookbook 'nodejs'
cookbook 'npm'
cookbook 'vim'
