# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

RUBY=/usr/local/ruby/2.1.5
PATH=$PATH:$HOME/bin:$RUBY/bin

export PATH
