# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

RUBY=/usr/local/ruby/2.2.2
PATH=$RUBY/bin:$PATH:$HOME/bin

export PATH
